### ISSUE TITLE
issue with old ui editing and creation

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#123]
I just used the old ui add media page to try to add a couple of media sources.  One of the media sources (http://classlink.com) was discovered as an existing one and work fine.  The other one was new and had a few problems:

* the url got set to he value 'true'
* when I tried to use the media edit page to fix the url, got a complaint about undef being  a bad boolean value from normalize_boolean_from_db() trigger by Controller/Admin/Media.pm line 579;
* when I fix that error by adding default values for the boolean fields, the edit saved to the database, but I got this error from the activities log:

> 2017-02-27 05:40:58,722 MediaWords.DBI.Activities: Writing activity failed: encountered object '0', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /home/hroberts/mediacloud/script/../lib/MediaWords/DBI/Activities.pm line 546.
2017-02-27 05:40:58,784 MediaWords.Controller.Root: Handling error: $VAR1 = [
>          'Caught exception in MediaWords::Controller::Admin::Media->edit_do "Logging one of the changes failed: encountered object \'0\', but neither allow_blessed, convert_blessed nor allow_tags settings are enabled (or TO_JSON/FREEZE method missing) at /home/hroberts/mediacloud/script/../lib/MediaWords/DBI/Activities.pm line 546."'
>        ];

-hal

**Comment by pypt** [comment]
Acknowledged, looking into it.

**Comment by hroberts** [comment]
also note that it would not be crazy just to delete the old ui code altogether if need be.  almost all of the functionality is in the new ui.  So if there are problems just specific to this specific code path, it would be ok to decide just to delete the whole code path (yay python and api transitions!).

-hal

**Comment by pypt** [comment]
Should be fixed. Fixes:

* A bunch of code was calling [HTTP::Request](http://search.cpan.org/~ether/HTTP-Message-6.11/lib/HTTP/Request.pm)'s `->url` method which 1) officially doesn't even exist, practically is a link to `->uri`, 2) returns URI object instead of an expected string, which Inline::Python somehow manages to convert to `True`. Replaced all such calls to `->uri->as_string`.
* In `media.full_text_rss` case, `normalize_boolean_for_db()` is now being called with as `my $allow_null = 1; normalize_boolean_for_db( $full_text_rss, $allow_null )` in order to allow NULL values. This confused me initially as `media.full_text_rss` allows NULL values and `stories.full_text_rss` doesn't.
* `normalize_boolean_for_db()` now treats empty strings as `false` (which is Catalyst's idea of false value).
* All of the code now uses (and should use in the future) `MediaWords::Util::JSON` helpers instead of vanilla `JSON` module. Said helpers are faster (as they use JSON::XS by default) and treat funky data (e.g. booleans) coming from Python correctly.

**Comment by pypt** [comment]
> also note that it would not be crazy just to delete the old ui code altogether if need be. almost all of the functionality is in the new ui. So if there are problems just specific to this specific code path, it would be ok to decide just to delete the whole code path (yay python and api transitions!).

I usually tend to nevertheless look through the code in order to figure out what the bug is and whether it's possible for the bug to reappear in other, less obvious places. However, if you're up for deleting some obsolete controllers, I'd be pleased to do that :).
