### ISSUE TITLE
Unit test suite requires internet connection

### ISSUE THREAD

**Issue by ColCarroll** [berkmancenter/mediacloud#239]
There are a few unit tests that require an internet connection.  These should either be run separately or removed.  See, for example, mediacloud/mediawords/util/test_web.py .

**Comment by pypt** [comment]
For the tests in `test_web.py`, it might be a good idea to rewrite them to use `hash_server`:

```python
from mediawords.test.http.hash_server import HashServer
from mediawords.util.network import random_unused_port

port = random_unused_port()
pages = { '/foo': 'Bar!' }
hs = HashServer(port=port, pages=pages)
hs.start()

# Do something with http://localhost:%(port)s/foo here

hs.stop()
```

See `test_user_agent.py` for more examples (`hash_server` can do many things, e.g. redirects, callbacks).

In some Perl unit tests, we sin a little and test the code against various live APIs (if credentials are set) in addition to local mock API implementations in order to make sure that both 1) our code is up to date to work against the specific API, and 2) their API hasn't changed in unpredictable ways. Nasty approach, but I haven't figured out a simpler way to do this, and it's rather effective (caught two Superglue feed outages this week with those unit-not-unit tests).

**Comment by pypt** [comment]
Won't fix (at least for now).
