### ISSUE TITLE
Investigate Solr performance problems

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#25]
We should make Solr start from Gradle (#23) and upgrade to Solr 6 (#24) first.

From Trello:

> since we reimported all of our solr stories, performance of the solr cluster seems much worse.  the `sentences/list` by date (which generates the dashboard histogram and is generated with a  `group.field=date` solr query) seems particularly bad.  I've poked at it a little bit and not found anything.  solr is great when it works but a black box when it doesn't.  the first thing to try might be just upgrading to 5.x.
> after watching it a bit today, one cause of the slowness is that we changed our sentence deduplication to only use an index for recent stories.  This isn't usually a problem because 99% of our stories are recent when we add them, but controversies end up spidering a lot of old stories, so the cm spider is ending up having to do lots of the slow, non-indexed queries on the `story_sentences` table (the queries are actually indexed by `media_id` and `publish_date`, just not by the sentence itself).  I don't think is the whole issue, but it's probably the biggest contributor right now.

**Comment by pypt** [comment]
How much of a speed up is still needed after 6.1.0 upgrade?

6.1.0 seems faster (most likely due to the fact the index got optimized and is now ~15-20 GB smaller, maybe some Solr performance improvements too), but not super-fast, one still has to wait for 10 s or so for *Pulse* and *Mentions* to appear in dashboard.

**Comment by pypt** [comment]
(We should have another look at performance after restarting story imports, that might be a performance hit by itself.)

**Comment by hroberts** [comment]
Yes, we should spend to digging into the performance.  On 4.6 even 
simple searches for the first few sentences, which is the thing that 
solr is tuned to do really well, were getting slow (several seconds in 
many cases).  Performance at that basic task seems much, much better 
now.  So we now have a huge head start in that that basic operation 
(upon which everything else is based) seems good now.

We need to dig into the dashboard queries to find out what the hold up is.

The mentions box still takes a long time to load, even though the simple 
sentences/list call is now quite fast.  So we should figure out if 
that's an api issue or a front end issue.  That box is also using 
sentences/count (which should be faster than sentences/list) and 
stories/count (which requires grouping by stories_id and so is a bit 
slower than sentences/count).  If Rahul is calling each of those in 
sequence, that could explain things.

The sentences/count call requires grouping by date.  I think that the 
new solr offers new methods for grouping that might make that query 
faster with some experimentation.

The other issue is that these individual calls may be quick but calling 
them all at once may swamp the cluster and make them much slower altogether.

What settings are using for the caches now?

It's also a good idea to look at comparison of and'ed queries sent to 
the q= parameters vs. using q= and fq= parameters.  I've gotten very 
different performance out of each at various times (and which is better 
has changed as our index has grown).  This is also heavily dependent on 
the cache configuration.

It would be great to have a little perl script that mimics the behavior 
of the dashboard in both calls made and the order and parallelization of 
the calls so that we can test this stuff sanely.

-hal

**Comment by pypt** [comment]
> What settings are using for the caches now?

Either the values copied from old `solrconfig.xml` or vendor's defaults: https://github.com/berkmancenter/mediacloud/blob/master/solr/mediacloud/collections/_base_collection/conf/solrconfig.xml#L441-L527

**Comment by hroberts** [comment]
First thing to try is to switch QueryResultCache to using maxRamMB with 
a pretty big setting (10GB?).

I think we should be able to use a bigger value for FilterCache as well 
once we are not terrified of the QueryResultCache running out of memory. 
  That should help with grouping performance.  It might also help if we 
start using more fq= queries.

Given more the more functional state of the QueryResultCache, we might 
play with sequencing of the dashboard queries.  For instance, it might 
be faster to run one of the widget queries first to get the basic query 
cached and then run the others off the cached data rather than making 
all of them hit the index.  I have no idea if that would work -- just 
wonderingh.

-hal

**Comment by hroberts** [comment]
will re-address after story index change.
