### ISSUE TITLE
setup rsync backups for solr

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#30]
We should use rsync to create a backup of the solr cluster files so that we can recover by simply copying the solr files back into place.

The best available space we have is on faith.law.harvard.edu, where we keep our postgres backups.

I've run the rsync a couple of times without pausing imports to solr just to create an rsync base and see how long the process should take.  I've run the rsync twice, with the second a day after the first, and the job took 12 hours the first time and 8 hours the second. 

To make this work, we will have to shut down imports to the solr for the period of the backup.  It's obviously not ideal to stop imports for 8 hours (and then wait ~12 hours for the data to restore to the machines in the case we need to recover), but I think this is the best we can do with our current resources.  The current alternative is that if solr goes down, we have to wait a few days to do the whole import process from scratch.

Things we can do in the medium term to make this work better:

* setup the spinning disk enclosure as network space and do the rsync to those disks on a local machine, which should greatly decrease the time required for backup and for restore;
* move the solr data onto a disk system that supports snapshots so that we can just pause imports for long enough for the few seconds to make the snapshot;
* once we have snapshotting available, experiment with just keeping one snapshot around on the solr cluster disks so that we have a way to virtually instantly recover for the modes of failure that the sort of software or user errors that have plagued us most.

**Comment by hroberts** [comment]
I have written a backup script on faith.law.harvard.edu that waits until mediawords_import_solr.pl is not running and then writes mcquery2:/tmp/solrbackup.lock and start an rsync from each of the solr machines.  When it is done, it removes the /tmp/solrbackup.txt.

I have also edited mediawords_import_solr.pl to check for /tmp/solrbackp.txt and die if it exists.

I expect the rsync to take 8-12 hours.

This is not the most robust solution, but it should work for the short term until we get move solr to a filesystem that will let us snapshot.

**Comment by Himanshusoni9** [comment]
One More issue : On  Solr Collection Data Backup Based on Condition/Data Filter.(There is no provision for that . )

Because SOLR BACKUP API with Query is not working
//http://localhost:8983/solr/admin/collections?action=RESTORE&name=myBackupName&location=C:\Users\DELL\Downloads\SOLR_BACKUP&collection=myCondCollection&query=text:cellphone

I am trying out to perform backups of our Solr data with a particular condition in mind.

To provide some context, let's say Solr collection consists of 100 records, among which 70 records contain the text "mobile," and the remaining 30 records contain the text "cellphone." my objective is to take a Solr collection/data backup that contains only the records the text "cellphone" – essentially, we want to create a backup file that reflects these 30 specific records only.

I would greatly appreciate it if you could share insights on the best practices or methods to achieve this selective backup based on a condition. If there are specific parameters or commands we should be utilizing, kindly provide the necessary guidance. Additionally, any documentation or references you could point us to would be immensely helpful.

Thank you in advance for your time and assistance. We value your expertise and look forward to implementing an efficient solution based on your recommendations.
