### ISSUE TITLE
MediaWords::Util::JSON::encode_json is very slow

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#374]
I've gotten very bad performance when calling the inline python version of MediaWords::Util::JSON::encode_json in a couple of cases.  One was for MediaWords::Solr::Dump, where I encode each story into json for import into solr.  That's performance critical, and switching to a perl XS json module resulted in about 10X speedup.  The other is the sentences/list api end point, which was taking over 20 seconds to encode about 8.5MB of json.  I switch to JSON::PP, and it is encoding now in about 1 second.

8.5MB is obviously a big chunk of data, but I'm worried we're losing a second or two to lots of our api calls to the simple json encoding.  And external folks do use our api to get big streams of data.  Switching MC_Controller_REST to using a perl encoder is non-trivial because the perl encoders do not like the Inline::Python::BOOLEAN objects.  I switched just the sentences/list call to use JSON:PP because I happen to know that its results do not include any booleans.

**Comment by pypt** [comment]
Python's JSON encoding routines are as fast as Perl's, but to encode something, we have to:

1) Convert it to Python's data types (done by `Inline::Python`)
2) Recursively iterate over a structure and convert Python's `bytes` to `str` (due to how `Inline::Python` works)
3) Run the Python subroutine / method (encode JSON)
4) Convert it back to Perl's data types (done by `Inline::Python`)
5) Recursively copy the whole returned object to be able to modify it later (which is done in many parts of the code)
6) Do some more postprocessing to improve compatibility

A good solution for this would be to rewrite more code to Python so that only the native code does the heavy lifting. "Temporary" fallback to Perl's libraries or selectively skipping steps from the list above only makes the rewrite harder (which already has mostly stalled due to day-to-day work).

For your listed cases, we could:

1) Rewrite [`list_get()`](https://github.com/berkmancenter/mediacloud/blob/master/lib/MediaWords/Controller/Api/V2/MC_REST_SimpleObject.pm#L308) so that it passes arguments to a native Python subroutine, fetches a resulting string JSON from it, and forwards it to Catalyst.
2) Rewrite Solr dumping to Python -- it doesn't look like it has many dependencies on the rest of our own code, and the dependencies that it does have are already rewritten to Python.

**Comment by pypt** [comment]
Closing for now.
