### ISSUE TITLE
fix parallel query error in postgres

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#388]
from topic 2255:

\Traceback (most recent call last): File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/result/result.py", line 77, in __execute cursor.execute(*query_args) File "/home/mediacloud/.virtualenvs/mediacloud/lib/python3.5/site-packages/psycopg2/extras.py", line 144, in execute return super(DictCursor, self).execute(query, vars) psycopg2.OperationalError: out of shared memory HINT: You might need to increase max_locks_per_transaction. CONTEXT: parallel worker During handling of the above exception, another exception occurred: Traceback (most recent call last): File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/handler.py", line 291, in query print_warnings=self.__print_warnings) File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/result/result.py", line 35, in __init__ print_warnings=print_warnings) File "/home/mediacloud/mediacloud/mediacloud/mediawords/db/result/result.py", line 114, in __execute 'mogrified_query': str(mogrified_query), mediawords.db.exceptions.result.McDatabaseResultException: Query failed: out of shared memory HINT: You might need to increase max_locks_per_transaction. CONTEXT: parallel worker ; query: ("select tl.* from topic_links tl, topic_stories ts\n where\n tl.link_spidered = 'f' and\n tl.stories_id = ts.stories_id and\n ( ts.iteration <= %(param_1)s or ts.iteration = 1000 ) and\n ts.topics_id = %(param_2)s and\n tl.topics_id = %(param_2)s\n\n limit %(param_3)s\n", {'param_3': 100000, 'param_1': 2, 'param_2': 2255}); mogrified query: b"select tl.* from topic_links tl, topic_stories ts\n where\n tl.link_spidered = 'f' and\n tl.stories_id = ts.stories_id and\n ( ts.iteration <= 2 or ts.iteration = 1000 ) and\n ts.topics_id = 2255 and\n tl.topics_id = 2255\n\n limit 100000\n"

**Comment by pypt** [comment]
That might have been me (or maybe a tandem of me running greedy queries for migrating story sentences to the partitioned table and you running greedy queries with `LIMIT 100000` in the topic mapper).

I think I came up with a way to copy sentences from the unpartitioned table to the partitioned one so that the copier is able to move sentences of ~100k stories (~1m sentences) in ~1 minute and not deal with the index bloat of the same time. Given the greediness of such a query (fetches 1m rows, sorts it to get distinct rows before insertion), I think it somehow managed to run out of database's `shared_buffers` (around 64GB) limit. How exactly did it happen is beyond my knowledge and imagination.

I've reduced the story chunk size (the count of stories the sentences of which get moved in a single run) from 100k to 50k, I hope this works and doesn't hit any limits.

**Comment by pypt** [comment]
Might have been all the advisory locks too:

http://www.databasesoup.com/2012/06/postgresqlconf-maxlockspertransaction.html

**Comment by hroberts** [comment]
That topic_links query was generating a different error a couple weeks ago when run against one of the giant election topics.  The 100k limit is a big reduction from the previous approach of just querying everything.

Also, I got the same error in the solr import script today, which makes me think it is either a system wide issue rather than a particular query or that, as you suggested, it is a problem with a particular postgres instance that persists across pooled uses of a connection by pgbouncer.

I'm going to go ahead and try rebooting postgres with max_locks_per_transaction at 1024.  Hopefully some combination of the above will fix things.

**Comment by hroberts** [comment]
... and now I see that you already restarted postgres.  I had already changed max_locks_per_transaction in the postgres file, so we are now running with the higher limit.  We can just watch to see if the error pops up again.

I just changed the max_locks_per_transaction setting directly in the postgres conf on mcdb1.  We'll have to add it to ansible if we want to keep the setting.

**Comment by pypt** [comment]
Added to Ansible's configuration.

**Comment by pypt** [comment]
Closing until we see another OOM :)
