### ISSUE TITLE
not parsing blaze articles correctly

### ISSUE THREAD

**Issue by allanko** [berkmancenter/mediacloud#41]
Lots of articles from theblaze.com aren't being #parsed correctly; it seems to be including text snippets from the sidebar/"popular stories" box, and therefore returning irrelevant stories for certain queries.

For example, story [463183765 ](http://www.theblaze.com/stories/2015/04/24/flashback-5-memorable-clashes-eric-holder-had-with-congress/) was returned by the query "Freddie Gray" (among many other irrelevant stories). It is actually a tribute to attorney general Eric Holder, but the story text as parsed by mediacloud includes the following:

<p><a title="Protesters Smash Out Police Car Windows and Storefronts as Thousands Rally for Freddie Gray (UPDATE: Baseball Fans Asked to Stay Inside Stadium)" rel="bookmark" href="http://www.theblaze.com/stories/2015/04/25/protesters-smash-out-police-car-windows-and-storefronts-as-thousands-rally-for-freddie-gray/">Protesters Smash Out Police Car Windows and Storefronts as Thousands Rally for Freddie Gray (UPDATE: Baseball Fans Asked to Stay Inside Stadium)</a></p>

**Comment by pypt** [comment]
Allan, thank you for your report!

We use [Readability](https://github.com/buriy/python-readability) for extracting text out of HTML articles. For theblaze.com, Readability erroneously decides that the "Read more stories" block that comes right after the article text is a part of the article's text too.

To mitigate this and similar problems (various more-or-less identical blocks mistaken as text, copyright notices repeated on each article, etc.), we split each article's text into distinct sentences and deduplicate them by comparing each new sentence to the list of sentences that we already have from a given news website. You can see that while the extracted article text for story 463183765 includes the "Read more stories" block, the list of sentences from the article text doesn't anymore (even though it still includes a couple of extra sentences that don't belong to a story).

Extracting text from a HTML page includes a lot of guesswork, so I don't really know whether and how the extraction could be improved without tailoring the extractor for each and every news website. If you have any ideas on that, please let us know!

**Comment by allanko** [comment]
From what you've said it seems like the sentence-comparison filter you described is successfully catching the extra story text, at least for theblaze.com. Would it make sense to remove those sentences from the story text as well as from the sentences list, so that words from the removed text don't get matched to the query and return false-positive results?

**Comment by pypt** [comment]
@hroberts, what do you think?

**Comment by hroberts** [comment]
So for general operation of media cloud, linas is correct that we deduplicate identical sentences in the same media source in the same calendar week.  This is precisely to catch these kinds of problems, which are very difficult for text extraction algorithms to deal with outside of the context of other stories.  What gets imported into our solr text index are the deduplicated sentences, so when you search solr, you won't get hits on sentences that have been successfully dedup'd.

We have an additional layer protection to try to mitigate this problem further when generating topics.  For topic relevancy, we have to not only match one of those deuplicated sentences, but the matching sentence can't even be the original version of a duplicate.  So any sentence that has a calendar week duplicate in the same media source fails the relevancy test within the topic spider.

Sadly, in this case, we are not detecting one of the Freddie Gray boilerplate sentence as a duplicate in either of these senses.  So we're just stuck with the results.

We haven't been able to come up with a good solution for this problem.  We spent a lot of time and effort researching the text extraction tool to minimize these sorts of problems, and we spend an enormous amount of our resources maintaining the ability to sentence deduplication (it's hard to efficiently and lookup index 6 billion+ sentences!).

An obvious solution is to add some custom scraping text for this specific site, but we have a very strict policy not to write any custom scraping code because it would very quickly make the whole project untenable to have to write and maintain thousands of custom scraping models   Our whole platform is based on the idea that solving these kinds of problems to a ~90% accuracy is good enough to get interesting and valid results.

I suspect what you are running into is that he social media data is telling you that this particular story is influential within the topic.  A major problem with using social media influence metrics is that they only tell you that the story was influential on social media and that it is minimally relevant to the topic.  Links, on the other hand, tell us both that the story was influential in the link economy and in almost all cases that it is highly relevant (because lots of links within the context of only stories relevant to a given topic is a strong relevancy indicator as well as influence indicator).

This is another problem that we have not solved.  Just looking at social media metrics within a topic is unlikely to be useful without manually filtering the list for relevancy of both the stories and the social media interest in the stories.  There are many minimally relevant stories about a given topic that gets lots of social media interest that is not relevant to the topic.  For instance think about a newspaper home page that happens to mention a topic one day and also has lots of social media influence -- the high social media influence in that case is very unlikely to be relevant to the topic.

**Comment by pypt** [comment]
Closing then, please reopen if needed.
