### ISSUE TITLE
support multiple machines in ansible deployment script

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#434]
We have production daemons running on three servers (mccore1, mcquery3, and mcquery1), and we should add support for automatic deployment for all three to ansible.

mcquery3 is running the fetch_link, topic_mine, topic_mine_public, and topic_snapshot daemons.  mccore1 is running the soon-to-daemonized import_solr_data.

**Comment by pypt** [comment]
Depends on https://github.com/berkmancenter/mediacloud/issues/425 I suppose, but https://github.com/berkmancenter/mediacloud/issues/425 is an easy task.

**Comment by pypt** [comment]
It turns out that our Ansible playbooks had everything in-place for the multiple machine deployments, I just forgot about it and thought it's going to be way more work :) So all I had to do was take care of a bunch of inconsistencies between our servers.

To deploy to multiple machines:

1. Make sure you have the latest `inventory/hosts.yml` (available on LastPass).
2. Do a test deployment:

```
cd ansible/
ansible-playbook -vvv --limit mctest deploy.yml
```

3. Do a production deployment:

```
cd ansible/
ansible-playbook -vvv deploy.yml
```

Please let me know if something doesn't work for you.
