### ISSUE TITLE
mediawords.solr.query throws an exception on single quote

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#449]
`mediawords.solr.query` throws an exception with input that has a single quote (`'`) in it:

```
\"/home/mediacloud/mediacloud/mediacloud/mediawords/solr/query.py\\", line 294, in get_inclusive_re\\n    return self.get_re(operands, inclusive=True)\\n  File \\"/home/mediacloud/mediacloud/mediacloud/mediawords/solr/query.py\\", line 258, in get_re\\n    term = shlex.split(term)[0]\\n  File \\"/usr/lib/python3.5/shlex.py\\", line 273, in split\\n    return list(lex)\\n  File \\"/usr/lib/python3.5/shlex.py\\", line 263, in __next__\\n    token = self.get_token()\\n  File \\"/usr/lib/python3.5/shlex.py\\", line 90, in get_token\\n    raw = self.read_token()\\n  File \\"/usr/lib/python3.5/shlex.py\\", line 166, in read_token\\n    raise ValueError(\\"No closing quotation\\")\\nValueError: No closing quotation\\""}
```

To reproduce, add a following test to `test_quote.py`:

```python
    # Single quote
    __validate_inclusive_re("Cote d'Ivoire", "(?: [[:<:]]Cote | [[:<:]]d'Ivoire )")
```

Maybe it would be worth it to consider reusing our language support modules instead of `shlex.split()` for tokenization? Or is this some exotic tokenization that is being done?

**Comment by hroberts** [comment]
fixed by replacing single quotes with spaces in solr/query.py.  the only valid use of single quotes in our solr queries is as apostrophes, and solr treats apostrophes as spaces any way.

the tokenizing done here is the programming language tokenization for the solr query itself, which has to support things like quoted strings as tokens, so our language tokenization modules won't help.  the shlex.split() function seems to be the most widely used python tokenizer for this sort of thing.  I had to work around some kinks in ways like this, but I think that's better than writing a tokenizer from scratch.
