### ISSUE TITLE
MediaCloud EC2 instructions error out

### ISSUE THREAD

**Issue by QasimQureshi** [berkmancenter/mediacloud#499]
I want to set-up a MediaCloud instance on EC2 using Vagrant, as described here (under the _On Amazon EC2_ heading):
https://github.com/berkmancenter/mediacloud/blob/master/doc/vagrant.markdown

I end up erroring out though.
![image](https://user-images.githubusercontent.com/3591082/47420911-f29a4f00-d798-11e8-8008-773261e6b20d.png)

So I've tried to specify an AMI in my Vagrant file, like so:
![image](https://user-images.githubusercontent.com/3591082/47421061-39884480-d799-11e8-9651-38b20652c6bb.png)

Now I run into errors over some SMB synced folders
![image](https://user-images.githubusercontent.com/3591082/47421122-6177a800-d799-11e8-9078-e500fefe38f6.png)

Any advice would be greatly appreciated! Do I need to set-up SMB storage (perhaps an S3 bucket)?

**Comment by pypt** [comment]
Hey Qasim!

As detailed in https://github.com/berkmancenter/mediacloud/blob/master/doc/vagrant.markdown#on-amazon-ec2, you have to set a bunch of environment variables, e.g. AWS's Access Key ID, Secret Access Key, ... to get the instance up. The AMI is [hardcoded](https://github.com/berkmancenter/mediacloud/blob/master/script/vagrant/Vagrantfile#L14) to a somewhat recent build of Ubuntu 16.04 (Xenial), Precise won't really work as it's a bit too old.

Also, are you running Vagrant from Windows (via Cygwin or something similar)? I haven't tried the AWS + Windows configuration yet, so that might be buggy. Your best bet (and a somewhat more tested path) is to either: 1) set up Vagrant using *nix OS, e.g. Linux or macOS; or 2) set up Vagrant on Windows + VirtualBox.

Let me know if that helps.

**Comment by QasimQureshi** [comment]
Thanks @pypt :)

I'm using MacOS Sierra (10.12.6). 

I am setting the environment variables like you said, like so -
![image](https://user-images.githubusercontent.com/3591082/47613931-7023cf00-dab9-11e8-8ed0-f39675fcb755.png)

But somehow I'm still getting asked for a SMB shared folder.

I looked through the Vagrantfile, and the only references to SMB folders are in the Windows if statement. Any idea what I'm doing wrong here?

**Comment by pypt** [comment]
I think in your case Vagrant is trying to be smart and reuse the virtual machine that you've created previously and deleted afterwards, so try:

* removing `~/.Trash/mediacloud-master/`
* removing `.vagrant/` from `script/vagrant/`

Also, to remove Vagrant instances cleanly, run `vagrant destroy` which takes care of all that stuff for you.

Works for me (c) with a recent Debian, Vagrant 2.2.0 and `vagrant-aws` 0.7.2.

**Comment by QasimQureshi** [comment]
I've gotten it deployed (on MacOS, I had to go to System Preferences > Sharing > File Sharing, and turn on SMB from the Options popup).

Also ended up using `run_install_test_suite_on_vagrant.sh`. When I ssh into my EC2 instance (using `vagrant ssh`), it gives errors about Perl dependencies not being present.

I wonder if I should manually install Perl5 or did I perhaps miss a step in deploying MediaCloud.. 

`
script/set_perlbrew_environment.sh: line 18: /home/ubuntu/perl5/perlbrew/etc/bashrc: No such file or directory
`

**Comment by pypt** [comment]
Probably the provisioning script didn't run fully for whatever reason. I'd reiterate that I recommend cleaning up your current Vagrant instances (from macOS's Trash too) and just rerunning `vagrant init` and `vagrant up` from the start as per the instructions.

Closing this issue for now, please do not hesitate to reopen it if you need more assistance.
