### ISSUE TITLE
Crawler gets stuck at `is_new()`

### ISSUE THREAD

**Issue by pypt** [berkmancenter/mediacloud#55]
Today I found crawler being stuck and not downloading anything for at least one hour.

When listing PostgreSQL locks, ~1340 [SELECTs from `MediaWords::DBI::Stories::is_new()`](https://github.com/berkmancenter/mediacloud/blob/master/lib/MediaWords/DBI/Stories.pm#L437-L447) where waiting for other SELECTs to complete.

Strangely enough, when crawler and other services were stopped (only `mediawords_queue_media_solr_exports.pl` and web server was running), the number of non-granted locks where increasing.

Practices about this particular code path that I find questionable:

* manual lock (`lock table stories in row exclusive mode`) in `FeedHandler.pm` (and `SELECT ... FOR UPDATE` in another module)
* `SELECT 1 ... FOR UPDATE` in `Stories.pm` without an actual `UPDATE` in the same subroutine (or at least a comment explaining what and where modifications are to be made)
* `SELECT 1 ... FOR UPDATE` -- does it even lock anything if only 1 is returned?
* `if ( $@ =~ /unique constraint \"stories_guid/ )` -- why do we trust PostgreSQL to return the same error message across versions? Aren't there better ways to do the same?

**Comment by hroberts** [comment]
You're right.  This is a mess.

The only solution I can think of that will actually do what it is supposed to without a universal select lock on 'stories' is an advisory lock like we use on story_sentences.  There's just no other way to prevent new stories from being written to the table while we query for stories that match the media_id / week / title.

The only downside I see for the advisory locks is that it is possible to write to the table without them, so we can't guarantee that we're not putting duplicate stories into the database by some other code path.  But the vast majority of our new stories come through the FeedHandler, and nothing catastrophic is going to happen if we end up with a small number of duplicate stories from some other source.  And the advisory locking is vastly simpler and faster than any alternative.

**Comment by pypt** [comment]
I strongly disagree, advisory locks are a huge workaround, and we have already used that card in `story_sentences`. If we employed them here too, we would end up having an even more state machine-y code than we already do.

If the purpose of the code is to skip INSERTing duplicate stories (without updating the duplicates that were found like in `story_sentences`), the proper, non-crying-in-the-shower solution is to proceed with a log-due 9.5 upgrade, add UNIQUE index on (media_id, week, title) and use [9.5's upsert](https://wiki.postgresql.org/wiki/What's_new_in_PostgreSQL_9.5#INSERT_..._ON_CONFLICT_DO_NOTHING.2FUPDATE_.28.22UPSERT.22.29). There are various ways to emulate the same behavior in 9.3 too.

**Comment by pypt** [comment]
What might have happened here (just guessing):

1. Crawler runs in multiple forks.
2. One of the forks sets a manual ROW EXCLUSIVE lock on `stories` making other forks wait for `stories` to get unlocked.
3. Fork that has set the lock dies somehow, PostgreSQL doesn't figure out that the client died and retains the lock.
4. The rest of the forks wait indefinitely.

Using advisory locks wouldn't have changed anything as they would still be kept after the fork going away. Unless you are planning to somehow query `pg_locks` manually and selectively unlock advisory locks that are deemed to be old enough to be considered invalid, in which case I'm going to start using heroin today to cope with the upcoming stress maintaining such a setup.

**Comment by hroberts** [comment]
I don't think #3 is possible.  If the client dies, postgres should always release the lock (otherwise all postgres locking would be fragile this way).  I think it's more likely there's a cycle of locks somehow, but I can't puzzle out how the cycle is created.

I'm fine with upsert as the long term solution.

In the short term, we don't actually need the update part of the upsert, so if we can just create a media_id / week / md5( title ) unique index and then check for a unique constraint failure in that or the media_id / guid unique index, we'd be fine.  I don't think there's any way of checking for a unique constraint error without looking at the error message, though.

I'm also okay with just letting this sit until we see it happen again.  The crawler has chewed along happily for a long time with this chunk of code in place without blocking itself.  We could leave it until we have done the 9.5 upgrade.

But we'll need to start creating that big media_id / week / md5( title ) unique index soon in any case.  I'm nervous that that query might take essentially forever to complete, but the only way to find out is to run it.

**Comment by pypt** [comment]
Agree with waiting for this to happen again (after all, Munin was able to catch this problem). Closing for now.
