### ISSUE TITLE
fetch_content() failing within webapp-api

### ISSUE THREAD

**Issue by hroberts** [berkmancenter/mediacloud#649]
when I try to call https://api.mediaclod.org/api/v2/downloads/single/920684423, I get this error:

```
{
"error": "Error(s): Caught exception in MediaWords::Controller::Api::V2::Downloads->single "Traceback (most recent call last): File "/opt/mediacloud/src/common/python/mediawords/dbi/downloads/store.py", line 212, in fetch_content download_storage_config=download_storage_config, File "/opt/mediacloud/src/common/python/mediawords/dbi/downloads/store.py", line 170, in _get_store_for_reading download_storage_config=download_storage_config, File "/opt/mediacloud/src/common/python/mediawords/dbi/downloads/store.py", line 61, in _get_amazon_s3_store if not amazon_s3_downloads_config.access_key_id(): File "/opt/mediacloud/src/common/python/mediawords/util/config/common.py", line 71, in access_key_id return env_value('MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID') File "/opt/mediacloud/src/common/python/mediawords/util/config/__init__.py", line 30, in env_value raise McConfigEnvironmentVariableUnsetException(f"Environment variable '{name}' is unset.") mediawords.util.config.McConfigEnvironmentVariableUnsetException: Environment variable 'MC_DOWNLOADS_AMAZON_S3_ACCESS_KEY_ID' is unset.""
}
```

When I look at the production docker-compose.yml, I see that env variable set in common.  But when I look at the env variables listed for the container in portainer, I don't see any of the common env variables.

**Comment by pypt** [comment]
You're right, somehow we forgot to include the "common" configuration (defined in `common-configuration` section and then "anchored in" via [YAML anchors](https://medium.com/@kinghuang/docker-compose-anchors-aliases-extensions-a1e4105d70bd) to relevant services' `environment`) to `webapp-api` service.

Fixed in 73980ba, change reflected in production `docker-compose.yml`, deployed everything.
