### ISSUE TITLE
Tips for contributors?

### ISSUE THREAD

**Issue by AlJohri** [berkmancenter/mediacloud#7]
I'd love to see a [```CONTRIBUTING```](https://github.com/blog/1184-contributing-guidelines) file outlining any guidelines for contributing to mediacloud. This is an amazing project, would love to see it get some more love from the open source community.

Is there anywhere I can read the project's current priorities and goals?

Thanks!

**Comment by pypt** [comment]
Hi Al,

Sorry for a rather late reply.

I'd suggest you to have a look at the [Get Access](http://mediacloud.org/get-involved/) page and consider signing up for access to our API. Don't miss the [Dashboard](https://dashboard.mediameter.org/) that you can use to play around with said API.

Also, you can try running Media Cloud yourself to collect some articles from your own list of media sources and have analysis of your own choosing with them. I'd suggest you try firing up our [Vagrant configuration](https://github.com/berkmancenter/mediacloud/blob/master/doc/vagrant.markdown) on a VM and play around with it.

Lastly, we're going to start using GitHub Issues instead of our internal issue tracker so there would be a chance for you to learn what we're working on.

Regards, Linas
